### PR TITLE
Remove client dep to fix Windows

### LINKED ISSUE #60: Failing tests related to allowed hosts in AssemblyScript
There is a CI failure first seen in #58:

```
thread 'tests::test_with_allowed_domains' 
panicked at 'called `Result::unwrap()` on an `Err` value: Exited with i32 exit status 1
wasm backtrace:
    0: 0x33eb - <unknown>!~lib/as-wasi/as-wasi/wasi_abort
    1: 0x431a - <unknown>!index/get
', tests/integration.rs:108:47
test tests::test_with_allowed_domains ... FAILED
```

Both failing tests seem to be the AssemblyScript ones, and both pass on my machine.
They should _just work_&trade; because none of these PRs introduce any changes to the way allowed hosts are handled:

```
cargo test --package wasi-experimental-http-wasmtime-sample --test integration --all-features -- tests::test_with_allowed_domains --exact --nocapture <

    Finished test [unoptimized + debuginfo] target(s) in 0.07s
     Running target/debug/deps/integration-39ca980876a4470e

running 1 test
module instantiation time: 1.2017504s
module instantiation time: 99.8947ms
test tests::test_with_allowed_domains ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 8 filtered out; finished in 2.97s

cargo test --package wasi-experimental-http-wasmtime-sample --test integration --all-features -- tests::test_async_with_allowed_domains --exact --nocapture <

    Finished test [unoptimized + debuginfo] target(s) in 0.06s
     Running target/debug/deps/integration-39ca980876a4470e

running 1 test
module instantiation time: 1.1927142s
module instantiation time: 99.2269ms
test tests::test_async_with_allowed_domains ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 8 filtered out; finished in 2.86s
```

### LINKED ISSUE #64: Compiling anything that imports `wasi_experimental_http_wasmtime` fails on Windows
This is because the `wasi_experimental_http_wasmtime` crate imports two functions from the `wasi_experimental_http` crate, which in turn relies on external symbols (the host functions related to HTTP).

And even if the two functions imported don't actually call any of the external symbols, the Windows linker still fails.

I will investigate if this is a known issue with the linker on Windows, but removing the dependency to `wasi_experimental_http` solves the issue, and the two functions are simple enough that we can just copy-paste.

```
  = note: libwasi_experimental_http-c7b972a7a58f275d.rlib(wasi_experimental_http-c7b972a7a58f275d.39shyjq0d6lqu8qa.rcgu.o) : 
error LNK2019: unresolved external symbol __imp_req referenced in function _ZN22wasi_experimental_http3raw3req17h295ccbc09f2fe42dE
          libwasi_experimental_http-c7b972a7a58f275d.rlib(wasi_experimental_http-c7b972a7a58f275d.39shyjq0d6lqu8qa.rcgu.o) : 
error LNK2019: unresolved external symbol __imp_header_get referenced in function _ZN22wasi_experimental_http3raw10header_get17h1870664f7a8646ffE
          libwasi_experimental_http-c7b972a7a58f275d.rlib(wasi_experimental_http-c7b972a7a58f275d.39shyjq0d6lqu8qa.rcgu.o) : 
error LNK2019: unresolved external symbol __imp_headers_get_all referenced in function _ZN22wasi_experimental_http3raw15headers_get_all17hb2f4ccc303974529E
          libwasi_experimental_http-c7b972a7a58f275d.rlib(wasi_experimental_http-c7b972a7a58f275d.39shyjq0d6lqu8qa.rcgu.o) : 
error LNK2019: unresolved external symbol __imp_body_read referenced in function _ZN22wasi_experimental_http3raw9body_read17h4cbd4ef921d4891cE
          D:\projects\deislabs\wasi-experimental-http\target\debug\deps\integration-159d744b0b153291.exe : fatal error LNK1120: 4 unresolved externals
```

### PR DESCRIPTION
**Pull request by radu-matei**
This commit removes the dependency on the client library from the
Wasmtime library in order to fix a Windows linking error.
Specifically, the Windows error stems from the fact that the client
library, which is mainly used for building Wasm modules, imports the
functions related to sending HTTP requests from the runtime.
There seems to be a bug in the Windows linker resulting in a linking
error, even if the Wasmtime crate is not calling any of the external
symbols, and this commit removes that dependency entirely, given that
the used functionality was limited to a single function.
See https://github.com/rust-lang/rust/issues/86125.

This also simplifies `build.rs`, ensuring it should run properly on both
Unix and Windows systems, and updates the GitHub action to compile on
Linux, macOS, and Windows.

close #60 
close #64

### CODE REVIEW

File: build.rs [hunk 1]
```diff
@@ -16,76 +18,93 @@ fn main() {
...
+            codegen_type,
+            "--output",
+            output,
+            "witx/wasi_experimental_http.witx",
+        ],
+        None,
+    );
+}
+
+fn run<S: Into<String> + std::convert::AsRef<std::ffi::OsStr>>(args: Vec<S>, dir: Option<String>) {
```
Comment (thomastaylor312) [inline build.rs:82]: Nit: `AsRef` should be imported by default. No need for the full path

Comment (thomastaylor312) [inline build.rs:82]: Nit: AsRef should be imported by default. No need for the full path

File: crates/wasi-experimental-http-wasmtime/src/lib.rs [hunk 2]
```diff
@@ -1,12 +1,12 @@
...
 use bytes::Bytes;
 use futures::executor::block_on;
-use http::{HeaderMap, HeaderValue};
+use http::{header::HeaderName, HeaderMap, HeaderValue};
 use reqwest::{Client, Method};
 use std::{cell::RefCell, collections::HashMap, rc::Rc, str::FromStr};
 use tokio::runtime::Handle;
 use url::Url;
-use wasi_experimental_http::header_map_to_string;
+// use wasi_experimental_http::header_map_to_string;
```
Comment (thomastaylor312) [inline crates/wasi-experimental-http-wasmtime/src/lib.rs:9]: Nit: Leftover debug

File: crates/wasi-experimental-http-wasmtime/src/lib.rs [hunk 3]
```diff
@@ -546,6 +546,52 @@ fn is_allowed(url: &str, allowed_hosts: Option<&[String]>) -> Result<bool, HttpE
...
 }
 
+// The following two functions are copied from the `wasi_experimental_http`
+// crate, because the Windows linker apparently cannot handle unresolved
+// symbols from a crate, even when the caller does not actually use any of the
+// external symbols.
+//
+// https://github.com/rust-lang/rust/issues/86125
+
+/// Decode a header map from a string.
```
Comment (thomastaylor312) [inline crates/wasi-experimental-http-wasmtime/src/lib.rs:556]: Should these be hidden since the "official" versions are in the client crate?

**Review by thomastaylor312 — APPROVED** [review]
